import Head from 'next/head'
import React from 'react'

type Props = {
    title: string;
    description: string;
}

const MetaHead = ({ title, description }: Props) => {
  return (
    <Head>
        <title>{ title }</title>
        <meta name="description" content={ description || "Generated by create next app"} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default MetaHead