import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import MetaHead from '@/common/components/MetaHead/MetaHead'
import { getLayout } from '@/common/components/Layout/Layout'
import { TextField } from '@/common/components/ui/TextField/TextField'
import { EyeOpenIcon } from '@radix-ui/react-icons'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <MetaHead title="Home" description="Generated by create next app" />
      <div>Home pageProps</div>
      <div
        style={{
          width: '100%',
          height: '100%',
          padding: '200px 400px 200px 400px',
        }}
      >
        <TextField type="email" label={'Email'} placeholder={'Enter Email'} />
        <TextField
          type="search"
          label={'Search'}
          placeholder={'Enter Search'}
        />
        <TextField
          type={'password'}
          label={'Password'}
          placeholder={'Enter Password'}
        />
      </div>
    </>
  )
}

Home.getLayout = getLayout
