import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import MetaHead from "@/common/components/MetaHead/MetaHead";
import { getLayout } from "@/common/components/Layout/Layout";
import {Button} from "@/common/components/ui/Button/Button";
import Dialog from "@/common/components/ui/Dialog/Dialog";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <MetaHead title="Home" description="Generated by create next app"/>
      <div>Home pageProps</div>
      <div className={styles.blo}>
          <Dialog
              title={'Email Sent'}
              trigger={<Button>Open</Button>}
          >
              <div>
                  lorem
              </div>
          </Dialog>
      </div>
    </>
  );
}

Home.getLayout = getLayout